services:
  rabbitmq:
      hostname: rabbitmq
      container_name: rabbitmq
      restart: unless-stopped
      image: rabbitmq:3.12.3-management-alpine
      env_file:
          - .env
      ports:
          - "5672:5672"
          - "15672:15672"

  redis:
    image: redis:alpine3.18
    volumes:
      - redis_data:/data
    ports:
        - "6379:6379"

volumes:
  redis_data:
    external: false
